version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      DATABASE_URL: /app/data/app.db

  db:
    image: alpine/sqlite3:latest
    volumes:
      - ./data:/data
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
